// This would typically come from an API
let checklistItems = [
  {
    id: 1,
    name: '北側壁面の塗装付着性の確認',
    part: 'walls',
    detail: 'paint',
    direction: 'north',
    status: 'pending',
    photos: [],
  },
  {
    id: 2,
    name: '壁のカビの兆候の確認',
    part: 'walls',
    detail: 'material',
    direction: 'north',
    status: 'pending',
    photos: [],
  },
  {
    id: 3,
    name: '北側窓の漏れの確認',
    part: 'walls',
    detail: 'window',
    direction: 'north',
    status: 'pending',
    photos: [],
  },
  {
    id: 4,
    name: '玄関ドアの密閉性の確認',
    part: 'walls',
    detail: 'door',
    direction: 'north',
    status: 'pending',
    photos: [],
  },
  {
    id: 5,
    name: '北側屋根の排水システムの確認',
    part: 'roof',
    detail: 'structure',
    direction: 'north',
    status: 'pending',
    photos: [],
  },
  {
    id: 6,
    name: '北側基礎の安定性の確認',
    part: 'foundation',
    detail: 'structure',
    direction: 'north',
    status: 'pending',
    photos: [],
  },
  {
    id: 7,
    name: '北側壁のひび割れの確認',
    part: 'walls',
    detail: 'structure',
    direction: 'north',
    status: 'pending',
    photos: [],
  },
  {
    id: 8,
    name: '北側壁の湿気レベルの確認',
    part: 'walls',
    detail: 'material',
    direction: 'north',
    status: 'pending',
    photos: [],
  },
  {
    id: 9,
    name: '北側屋根の瓦の状態確認',
    part: 'roof',
    detail: 'material',
    direction: 'north',
    status: 'pending',
    photos: [],
  },
  {
    id: 10,
    name: '北側の断熱システムの確認',
    part: 'walls',
    detail: 'structure',
    direction: 'north',
    status: 'pending',
    photos: [],
  },

  // EAST direction items (10 items)
  {
    id: 11,
    name: '東側の塗装の色褪せの確認',
    part: 'walls',
    detail: 'paint',
    direction: 'east',
    status: 'pending',
    photos: [],
  },
  {
    id: 12,
    name: '東側窓ガラスの確認',
    part: 'walls',
    detail: 'window',
    direction: 'east',
    status: 'pending',
    photos: [],
  },
  {
    id: 13,
    name: '東側ドアの耐久性の確認',
    part: 'walls',
    detail: 'door',
    direction: 'east',
    status: 'pending',
    photos: [],
  },
  {
    id: 14,
    name: '東側基礎のひび割れの確認',
    part: 'foundation',
    detail: 'structure',
    direction: 'east',
    status: 'pending',
    photos: [],
  },
  {
    id: 15,
    name: '東側庇の状態確認',
    part: 'roof',
    detail: 'structure',
    direction: 'east',
    status: 'pending',
    photos: [],
  },
  {
    id: 16,
    name: '雨どい排水管の確認',
    part: 'walls',
    detail: 'material',
    direction: 'east',
    status: 'pending',
    photos: [],
  },
  {
    id: 17,
    name: '東側屋根の瓦の状態確認',
    part: 'roof',
    detail: 'material',
    direction: 'east',
    status: 'pending',
    photos: [],
  },
  {
    id: 18,
    name: '東側壁の接合部の確認',
    part: 'walls',
    detail: 'structure',
    direction: 'east',
    status: 'pending',
    photos: [],
  },
  {
    id: 19,
    name: '東側壁の垂直性の確認',
    part: 'walls',
    detail: 'structure',
    direction: 'east',
    status: 'pending',
    photos: [],
  },
  {
    id: 20,
    name: '東側防水システムの確認',
    part: 'foundation',
    detail: 'material',
    direction: 'east',
    status: 'pending',
    photos: [],
  },

  // SOUTH direction items (10 items)
  {
    id: 21,
    name: '南側壁面の塗装剥がれの確認',
    part: 'walls',
    detail: 'paint',
    direction: 'south',
    status: 'pending',
    photos: [],
  },
  {
    id: 22,
    name: '窓の日よけシステムの確認',
    part: 'walls',
    detail: 'window',
    direction: 'south',
    status: 'pending',
    photos: [],
  },
  {
    id: 23,
    name: '南側ドアの断熱性の確認',
    part: 'walls',
    detail: 'door',
    direction: 'south',
    status: 'pending',
    photos: [],
  },
  {
    id: 24,
    name: '基礎の収縮現象の確認',
    part: 'foundation',
    detail: 'structure',
    direction: 'south',
    status: 'pending',
    photos: [],
  },
  {
    id: 25,
    name: '南側屋根の断熱性の確認',
    part: 'roof',
    detail: 'material',
    direction: 'south',
    status: 'pending',
    photos: [],
  },
  {
    id: 26,
    name: 'バルコニードアの状態確認',
    part: 'walls',
    detail: 'door',
    direction: 'south',
    status: 'pending',
    photos: [],
  },
  {
    id: 27,
    name: '壁タイルの品質確認',
    part: 'walls',
    detail: 'material',
    direction: 'south',
    status: 'pending',
    photos: [],
  },
  {
    id: 28,
    name: '屋根の排水能力の確認',
    part: 'roof',
    detail: 'structure',
    direction: 'south',
    status: 'pending',
    photos: [],
  },
  {
    id: 29,
    name: '南側基礎の沈下の確認',
    part: 'foundation',
    detail: 'structure',
    direction: 'south',
    status: 'pending',
    photos: [],
  },
  {
    id: 30,
    name: '基礎周りの水溜りの確認',
    part: 'foundation',
    detail: 'material',
    direction: 'south',
    status: 'pending',
    photos: [],
  },

  // WEST direction items (10 items)
  {
    id: 31,
    name: '西側塗装の耐熱性の確認',
    part: 'walls',
    detail: 'paint',
    direction: 'west',
    status: 'pending',
    photos: [],
  },
  {
    id: 32,
    name: '雨に強い窓の密閉性確認',
    part: 'walls',
    detail: 'window',
    direction: 'west',
    status: 'pending',
    photos: [],
  },
  {
    id: 33,
    name: '西側ドアのゴムパッキンの確認',
    part: 'walls',
    detail: 'door',
    direction: 'west',
    status: 'pending',
    photos: [],
  },
  {
    id: 34,
    name: '西側基礎周りの排水確認',
    part: 'foundation',
    detail: 'structure',
    direction: 'west',
    status: 'pending',
    photos: [],
  },
  {
    id: 35,
    name: '西側屋根材の耐久性確認',
    part: 'roof',
    detail: 'material',
    direction: 'west',
    status: 'pending',
    photos: [],
  },
  {
    id: 36,
    name: '壁の防水性能の確認',
    part: 'walls',
    detail: 'material',
    direction: 'west',
    status: 'pending',
    photos: [],
  },
  {
    id: 37,
    name: '西側屋根の排水システム確認',
    part: 'roof',
    detail: 'structure',
    direction: 'west',
    status: 'pending',
    photos: [],
  },
  {
    id: 38,
    name: '基礎に影響する樹木の確認',
    part: 'foundation',
    detail: 'material',
    direction: 'west',
    status: 'pending',
    photos: [],
  },
  {
    id: 39,
    name: '熱膨張によるひび割れの確認',
    part: 'walls',
    detail: 'structure',
    direction: 'west',
    status: 'pending',
    photos: [],
  },
  {
    id: 40,
    name: '屋根の避雷システムの確認',
    part: 'roof',
    detail: 'structure',
    direction: 'west',
    status: 'pending',
    photos: [],
  },
];
